#!/usr/bin/env bash
#Script that displays numbers from 1 to 100, multiple of 3 and 5
m=1 
for((i=1;i<101;i++)) ;{ 
    ((n=m*i))
 if ((n%5==0 && n%3==0)) 
 then
     echo "FizzBuzz" 
 elif ((n%3==0))
 then
     echo "Fizz"
 elif ((n%5==0))
 then
     echo "Buzz"
 else
     echo $i
 fi 
}
