#!/usr/bin/env bash
#Script to tell the story of passwd
while IFS=":" read -r A B C D E F G
do
    echo "The user $A is part of the $D gang, lives in $F and rides $G. $C's place is protected by the passcode $B, more info about the user here: $E"
done < /etc/passwd
