#!/usr/bin/env bash
#This script displays the content of the current directory, in list where displayed the name.
for list in $(find . -not -name '*.*' | cut -d "-" -f2-)
do
    echo "$list"
 done
    
