#!/usr/bin/env bash
#Script that gives you information about the school file.
FILE=9-to_file_or_not_to_file
if [ -f "$FILE" ]; then
    echo "school file exists"
    if [ -s "$FILE" ]; then
	echo "school file is not empty"
	if [ -d != "$FILE" ]; then
	    echo "school is a regular file"
        fi
    else
	echo "school file is empty"
	if [ -d != "$FILE" ]; then
            echo "school is a regular file"
        fi
    fi
else 
    echo "school file does not exist"
fi
