#!/usr/bin/env bash
#Write Bash (init) script "11-manage_my_process" that manages "manage_my_process"
#function entrada(){
#   
#   
#}
#entrada 

case "$1" in
    "start")
	echo "$$" > /var/run/my_process.pid
	echo "manage_my_process started"
	sh manage_my_process
	;;
    "stop")
	rm /var/run/my_process.pid
	pkill -f manage_my_process
	echo "manage_my_process stopped"
        ;;
    "restart")
	rm /var/run/my_process.pid
	echo "$$" > /var/run/my_process.pid
        pkill -f manage_my_process
	sh manage_my_process
	echo "manage_my_process restarted"
	       ;;
    *)
	echo "Usage: manage_my_process {start|stop|restart}"
esac
